question_data = [{"text": "A slug's blood is green.", "answer": "True"},
                 {"text": "The loudest animal is the African Elephant.", "answer": "False"},
                 {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
                 {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
                 {"text": "In West Virginia, USA, if you accidentally hit an animal with your "
                          "car, you are free to take it home to eat.", "answer": "True"}, {
                     "text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.",
                     "answer": "False"}, {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
                 {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
                 {"text": "Google was originally called 'Backrub'.", "answer": "True"},
                 {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
                 {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
                 {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}]

question_data_alt = [{"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                      "question": "&quot;Typewriter&quot; is the longest word that can be typed using only the first row on a QWERTY keyboard.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                      "question": "Coca-Cola&#039;s original colour was green.", "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                      "question": "The US emergency hotline is 911 because of the September 11th terrorist attacks.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                      "question": "The sum of all the numbers on a roulette wheel is 666.", "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                      "question": "An eggplant is a vegetable.", "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                      "question": "You are allowed to sell your soul on eBay.", "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                      "question": "Fast food restaurant chains Carl&#039;s Jr. and Hardee&#039;s are owned by the same company.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                      "question": "&quot;Santa Claus&quot; is a variety of melon.", "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                      "question": "Popcorn was invented in 1871 by Frederick W. Rueckheim in the USA where he sold the snack on the streets of Chicago.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                      "question": "The British organisation CAMRA stands for The Campaign for Real Ale.",
                      "correct_answer": "True", "incorrect_answers": ["False"]}]
